### ISSUE TITLE
Advisory board - first meeting

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#198]
plan

**Comment by PatReynolds** [comment]
Ideas sent by email 23/12/2016

**Comment by DeniseColbert** [comment]
Tentative agenda: https://docs.google.com/document/d/18QbGT9kMTkdKOQjbPig7Ka7btkhz2Zlk1m-y62km81k/edit#

**Comment by PatReynolds** [comment]
@DeniseColbert agenda is fine

**Comment by DeniseColbert** [comment]
Thanks. Which, if any, trustees should i ask along?

Kind regards,

Denise

**********
Denise Colbert
Engagement Co-ordinator

E: denise.colbert@freeukgen.org.uk
T: +44 7825 338014
W: http://www.freeukgenealogy.org.uk/

Free UK Genealogy
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484.

VAT registration: 233 0105 70

On 19 Jan 2017 16:02, "PatReynolds" <notifications@github.com> wrote:

@DeniseColbert <https://github.com/DeniseColbert> agenda is fine

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/FreeUKGen/Coordination/issues/198#issuecomment-273816298>,
or mute the thread

**Comment by Captainkirkdawson** [comment]
Should there not be a review of Terms of Reference? or Expectations?

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DeniseColbert** [comment]
Meeting note draft completed- will send out once signed off by you, along with questionnaire on date/time preferences for meetings.

**Comment by PatReynolds** [comment]
Pat to create group on freeukgen@gmail.com and make Denise manager.

**Comment by DeniseColbert** [comment]
Are project members ok to disseminate board info / how much?
