### ISSUE TITLE
Add Google analytics code to www.FreeUKGen pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#249]
@bev-fc Please add script to 
homepage
volunteering
donate
FreeBMD 'landing' page
FreeCEN 'landing' page
FreeREG 'landing' page

**Comment by bev-fc** [comment]
Pat, can you elaberate the requirement? The code was added into the header, it is site-wide, no need to add to each page individually

**Comment by PatReynolds** [comment]
@DavidVerne  can you explain what you need?

**Comment by PatReynolds** [comment]
David says: I checked Google Analytics this yesterday and it hasnt recorded any data yet
I think the code has to be pasted into the body - I will check on this.

**Comment by bev-fc** [comment]
Hi David, the code was added into the header, and there is no need to be pasted into each page, because each page inherits the <head> automatically. I don't know how to upload an image file to waffle, please have a look at this link: https://s24.postimg.org/s7xfkf0ph/Screen_Shot004.jpg (it is a free image host, I don't know how long they will keep this file, please let me know if you can not see the image), it is a screenshot of google analytics, as you can see, the data is being collected, for each page everyday. Could you give me more detail when you mentioned to paste the code into FreeUKGen, what code you are referring to? I am still lost what data do you want, can you be more specific?

**Comment by Captainkirkdawson** [comment]
@bev-fc   you upload images into the waffle by doing so on the actual github issue

The waffle is just a manipulation of Github issue information so to do anything special you just go the the specific github issue

**Comment by bev-fc** [comment]
Sorry everyone,  I guess I deleted the comment by mistake. Let me post it again. Thanks Kirk, I tried to attach image from github this time. 

Hi David, the code was added into the header, there is no need to be pasted into each page, because each page inherits the < head > tag automatically. I don't know how to upload an image file to waffle, please have a look at this link: https://s24.postimg.org/s7xfkf0ph/Screen_Shot004.jpg and https://s27.postimg.org/ic47dhrwz/Screen_Shot005.jpg (it is a free image host, I don't know how long they will keep this file, please let me know if you can not see the image), it is a screenshot of google analytics for freeUKGen, as you can see, the data is being collected, for each page everyday. Could you give me more detail when you mentioned to paste the code into FreeUKGen, what code you are referring to? I am still lost what data do you want, can you be more specific?

![screenshot001](https://cloud.githubusercontent.com/assets/22349799/22791516/9d71678c-eeb7-11e6-9ac9-0d2d708decd8.jpg)
![screenshot002](https://cloud.githubusercontent.com/assets/22349799/22791515/9d6c8b68-eeb7-11e6-9b3e-221ee2294527.jpg)

**Comment by bev-fc** [comment]
Any further question regarding this issue?

**Comment by PatReynolds** [comment]
Pat to check with Mike and Anna that they have the information they need

**Comment by PatReynolds** [comment]
Thanks, @bev-fc I have now finished my analytics basic training, and everything we need seems to be there, so closing with thanks.
