### ISSUE TITLE
Check Barrie's review of Donate vs current situation

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#516]

**Comment by richpomfret** [comment]
Here's the feedback (within context up updating BMD site to include new donate button) - we need to check this with the stories we already have for this page and ammend as we see fit:

1) When I tried to copy the animated graphic from Free UK Generalogy I discovered it was extremely complicated and took up 23KB! And I couldn't actually get it to work on the FreeBMD website (I didn't try that hard). If we are going to put it on every page it needs to have a much smaller footprint, I would suggest just a simple gif.

2) The Free UK Genealogy website is not properly engineered (e.g. not resilient) or managed (e.g. not monitored) ... I describe it as "experimental" ... so linking to it from a production system is dubious. I have been complaining about this for a considerable time.

3) Donations are similar to what in marketing terms is known as a "grudge purchase" (buying car tyres is the classic example) and therefore anything in the process that turns people off is more likely to make them give up. The first negative is that one clicks on a link in FreeBMD to be taken to an organisation one has (probably) never heard of. The first thing the page should therefore say is that FreeBMD is part of Free UK Genealogy and in this sense I believe the donate page should be tailored to the project it has been linked from.

4) The donations page on Free UK Genealogy has been cleaned up but it still lacks the simplicity and clarity of the FreeBMD page (not that I am claiming the FreeBMD page is the bee's knees).

5) The first major heading is "How to help" which starts off with ways to help other than by donating. Whilst this information is important it is confusing having it as the first thing you read about when the subject in question is donating. The "other ways to help" should be in a sidebar to show that  it addresses a different, but related, topic.

6) There should, like the FreeBMD page, be a summary of the ways to donate and the pros and cons.

7) The MyDonate text says you cannot yet Gift Aid but if you go to the link you can.

8) The GoCardless links should be compacted, say £2, £5, etc as buttons across the page - the actual link should not be shown.

9) We still have the nonsense of people being expected to open a PDF form, not to fill it in, but to read the conditions - the conditions should just be transferred to the main page - they are only a couple of sentences.

10) Transferring to a different page for non-Gift Aid is confusing because both pages look similar and there is no visual clue as to whether or not one is Gift Aiding. Why not just have different buttons or a tick box? The Gift Aid form could open up if you ticked Gift Aid.

11) If you use GoCardless and Gift Aid it is not possible to see what the process is (without a actually setting up a direct debit) so there might be some gremlins lurking in this path (there might not even be a Gift Aid declaration).

12) Under GoCardless it says "Go Cardless regret that payment from other currencies' accounts are not available yet". There is an ambiguity here in that it could refer to Euro and Krone as well. This could be removed by saying "We regret ..."

13) The page lacks the statement that if a person's tax circumstances change so that they are no longer eligible for Gift Aid they must  contact us (see FreeBMD page).

14) There is no contact point for help (see FreeBMD page).
