### ISSUE TITLE
Live preview not working in Craft

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#522]

**Comment by DeniseColbert** [comment]
@PatReynolds FYI - Bev's response to LP not opening links in-tab: The site sets x-frame-options to SAMEORIGIN and they are different domain from www.freeukgenealogy.org.uk, control panel uses ajax so it's blocked. Because control panel uses ajax, after switched to https, you may see many rejections due to cross domain violation. A work around will be use open link in new tab to 'jump out of' control panel.
