### ISSUE TITLE
Investigate placing our adverts on our sites

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/Coordination#682]

**Comment by DeniseColbert** [comment]
Google support have no idea! Can't find guidance, but they have sent a link to the relevant forum where I can ask about Ad grants / Display Ads.

**Comment by DeniseColbert** [comment]
Finally! Found the answer: 

![image](https://user-images.githubusercontent.com/19173257/42318966-7c8ad6b0-8048-11e8-8e85-b3c33e3c8950.png)

So that's a no, through Adwords via ad grant. However, it may be worth considering: a) having our own 'ads' display to users, and b) spending some money to display our ads on 'managed placement' websites (e.g. John Lewis, SAGA etc)

**Comment by PatReynolds** [comment]
Thanks! Yes, targeted advertising to "our" demographic is certainly
something to consider.

On the main website, I'd rather keep it uncluttered. If we want to make an
"advert" for something, we wouldn't need to go via Google (unless there is
some advantage that escapes me).

Best wishes,

Pat

Executive Director, Free UK Genealogy

**Comment by DeniseColbert** [comment]
I don't think we need 'ads' for the projects on the main sites, but could have them on the project websites to encourage users to visit. We already have the logos of other projects above the footer, maybe make them into more of an ad?
