### ISSUE TITLE
Fix analytics on FUG site

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/Coordination#901]
Analytics dropped when cookie code implemented in May. We had the wrong UA tag which was fixed on 6th Sept, but numbers were still very low (~250 compared to ~1500 pre-May).

20th Sept, Bev made the cookie banner/text bigger to encourage clicks, and numbers increased to ~550. This is based on only 3 days of data but still seems low. 

We are hoping that anonymous IP and (maybe?) GTM will help 'fix' the issue, but there may also be a problem with timing / pageview triggering.

**Comment by richpomfret** [comment]
Anonymous IP was already implemented by Bev (which is a very good thing). However, we might need to ensure/check that the page is auto refreshed when the user clicks 'accept' for the cookies so that the pageview is then sent to GA. It looks like we ARE currently using a couple of GA Advertising Features for this site and therefore unfortunately it is most likely we do still require consent for users before the cookie fires...

**Comment by richpomfret** [comment]
We may be able to distinguish between the 1st party and 3rd party GA cookies we use. IF that is the case, we can trigger 1st party when a user visits the site, then 3rd party IF the user hits 'accept'. We do also need to give the user the ability to toggle these options on/off via the cookie policy page.

**Comment by DeniseColbert** [comment]
The work Bev did on Tuesday has brought us back up to the ball-park of pre-GDPR change numbers of visitors. Hurrah, and thanks!
